FROM php:7.4-apache

RUN apt update
RUN apt install -y nano 
RUN apt install -y git

WORKDIR /var/www/html

RUN echo "Hola soy emilio" > /var/www/html/index.html
RUN echo "<?php phpinfo(); ?>" > /var/www/html/info.php